#FROM huggingface/transformers-pytorch-gpu:latest
#ENV PYTHONUNBUFFERED 1
#ENV SHELL /bin/bash
#WORKDIR /opt
#
#COPY requirements.txt /opt/
#RUN python3 -m pip install -r requirements.txt

#FROM ubuntu:18.04
FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04
LABEL maintainer="Hugging Face"
LABEL repository="transformers"
ENV PYTHONUNBUFFERED 1
ENV SHELL /bin/bash
WORKDIR /opt

RUN apt update && \
    apt install -y bash \
                   build-essential \
                   git \
                   curl \
                   ca-certificates \
                   python3 \
                   python3-pip && \
    rm -rf /var/lib/apt/lists

RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir \
    mkl \
    torch

COPY requirements.txt /opt/
RUN python3 -m pip install -r requirements.txt

#COPY . transformers/
COPY . opt/
RUN mkdir transformers
COPY transformers transformers/
#RUN git clone https://github.com/huggingface/transformers

RUN cd transformers/ && \
    python3 -m pip install --no-cache-dir .

CMD ["/bin/bash"]
